name: DeepSource Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deepsource:
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{ github.event.pull_request.html_url || '' }}
      DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install DeepSource CLI
        run: curl https://deepsource.io/cli | sh

      - name: Run DeepSource Analysis
        run: ./bin/deepsource report --analyzer javascript

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Auto-merge if DeepSource passes
        if: success()
        run: |
          gh pr merge "$PR_URL" --merge --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
