name: DeepSource Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  deepsource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run DeepSource Analysis
        uses: deepsource/action@v0.1
        with:
          token: ${{ secrets.DEEPSOURCE_TOKEN }}

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Auto-merge if DeepSource passes
        if: success()
        run: |
          gh pr merge "${{ github.event.pull_request.html_url || '' }}" --merge --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
